# This workflow builds and deploys your website

name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Обновлено до актуальной LTS-версии Node.js, чтобы убрать Warning

      - name: Install dependencies
        # Используем npm install вместо npm ci, так как у вас локально нет файла package-lock.json
        run: npm install 
      
      - name: Build project
        run: npm run build --if-present # Флаг --if-present не даст упасть, если скрипта build нет в package.json
      
      - name: Run tests
        run: npm test --if-present # Флаг --if-present не даст упасть, если тесты еще не написаны
